apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../argocd/
  - ../../cert-manager/staging/
  - ../../external-dns/staging/
  - ../../external-secrets/
  - ../../grafana/
  - ../../istio/staging/
  - ../../tailscale/
