replicaCount: 2

image:
  tag: "latest"

ingress:
  enabled: true
  hosts:
    - host: app.iqbalhakim.ink
      paths:
        - path: /
          pathType: Prefix
    - host: iqbalhakim.ink
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
