---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-ingress-gateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingress
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - grafana.prod.iqbalhakim.ink
        - argo.prod.iqbalhakim.ink
        - rollouts.prod.iqbalhakim.ink
        - prometheus.prod.iqbalhakim.ink
        - litmus.prod.iqbalhakim.ink
        - app.iqbalhakim.ink
        - api.iqbalhakim.ink
        - iqbalhakim.ink
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - grafana.prod.iqbalhakim.ink
        - argo.prod.iqbalhakim.ink
        - rollouts.prod.iqbalhakim.ink
        - prometheus.prod.iqbalhakim.ink
        - litmus.prod.iqbalhakim.ink
        - app.iqbalhakim.ink
        - api.iqbalhakim.ink
        - iqbalhakim.ink
      tls:
        mode: SIMPLE
        credentialName: iqbalhakim-prod-tls
