apiVersion: v1
kind: Service
metadata:
  name: istio-ingress
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.iqbalhakim.live,argocd.iqbalhakim.live
    tailscale.com/hostname: "iqbalhakim-ingress"
