apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

patches:
  - path: external-secrets.yaml
  - path: admission-patch.yaml
  - path: grafana-config-patch.yaml
  - path: replicas-patch.yaml
  - path: ha-patch.yaml
