apiVersion: v1
kind: Secret
metadata:
  name: aws-sm-credentials
  namespace: external-secrets
type: Opaque
stringData:
  access-key: <AWS_ACCESS_KEY_ID>
  secret-access-key: <AWS_SECRET_ACCESS_KEY>
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-sm-credentials
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: aws-sm-credentials
            namespace: external-secrets
            key: secret-access-key
