apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../argocd/prod/
  - ../../argo-image-updater/
  - ../../argocd/apps/
  - ../../cert-manager/prod/
  - ../../external-dns/prod/
  - ../../external-secrets/
  - ../../grafana/prod/
  - ../../istio/prod/
  - ../../tailscale/
